apiVersion: v1
kind: ConfigMap
metadata:
  name: bull-signal-bot-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "bull-signal-bot.name" . }}
data:
  EMAILS: "{{ .Values.config.EMAILS }}"
