apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bull-signal-bot.fullname" . }}
spec:
  schedule: "15 6 * * *"  # Every day at 6:15 AM
  selector:
    matchLabels:
      app: {{ include "bull-signal-bot.name" . }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: bull-signal-bot
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              {{- range .Values.envFromSecrets }}
                - name: {{ .name }}
                  valueFrom:
                    secretKeyRef:
                      name: bull-signal-bot-secrets
                      key: {{ .key }}
              {{- end }}
              {{- range .Values.envFromConfigMap }}
                - name: {{ .name }}
                  valueFrom:
                    configMapKeyRef:
                      name: bull-signal-bot-config
                      key: {{ .key }}
              {{- end }}

