apiVersion: v1
kind: Service
metadata:
  name: {{ include "bull-signal-bot.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "bull-signal-bot.name" . }}
