# cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bull-signal-bot
  namespace: bull-signal-bot
spec:
  schedule: "15 14 * * *"  # 6:15 AM PST
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bull-signal-bot
            image: edguillen/bull-signal-bot:latest
            envFrom:
            - secretRef:
                name: bull-signal-bot-secrets
          restartPolicy: Never
