replicaCount: 1

image:
  repository: eguillen33/bull-signal-bot
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

envFromSecrets:
  - name: FMP_API_KEY
    valueFrom:
      secretKeyRef:
        name: bull-signal-bot-secrets
        key: FMP_API_KEY

  - name: EMAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: bull-signal-bot-secrets
        key: EMAIL_PASSWORD

envFromConfigMap:
  - name: EMAILS
    key: EMAILS

config:
  EMAILS: "id4eguillen@gmail.com,edguillen87@hotmail.com"

