replicaCount: 1

image:
  repository: eguillen33/bull-signal-bot
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

envFromSecrets:
  - name: FMP_API_KEY
    key: FMP_API_KEY
  - name: EMAIL_PASSWORD
    key: EMAIL_PASSWORD

envFromConfigMap:
  - name: EMAILS
    key: EMAILS
  - name: EMAIL_SENDER
    key: EMAIL_SENDER

config:
  EMAILS: "id4eguillen@gmail.com,edguillen87@hotmail.com"
  EMAIL_SENDER: "id4eguillen@gmail.com"

