name: Bull Signal Bot CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Run Flake8 (Code Smell & Style Check)
        run: flake8 .

  security:
    name: Security & Dependency Scanning
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Install security tools
        run: pip install bandit pip-audit
      
      - name: Run Bandit (Python Security Scan)
        run: bandit -r .

      - name: Run pip-audit (Dependency Vulnerability Check)
        run: pip-audit
        
  secret-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for secrets with GitGuardian
        uses: GitGuardian/ggshield-action@v1
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [security, secret-scan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/

  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/setup-python@v4

      - name: Build Docker Image
        run: docker build -t bull-signal-bot:latest .

  image-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "bull-signal-bot:latest"
          format: "table"
          severity: "CRITICAL, HIGH"

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [image-scan]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
#      - name: Authenticate with AWS
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: aws eks --region us-west-2 update-kubeconfig --name edguillen-k8s-cluster

#      - name: Deploy to EKS
#        run: |
#          kubectl apply -f k8s/deployment.yaml
#          kubectl rollout status deployment/bull-signal-bot

      - name: Deploy Application
        run: echo "Deploying application..."
